### ISSUE TITLE
Import recipe files?

### ISSUE THREAD

**Issue by iangreenleaf** [qgriffith/OpenEats#16]
I'd love to see the ability to import recipes from elsewhere. Looks like MealMaster format would be consistent and a good option (at least as a lowest common denominator). Has any work been done towards this sort of ability? Is it a feature you'd like to see? I might be able to contribute a patch towards this end; I'm mostly a Rails dev but can hack my way around Python.

**Comment by the4ndy** [comment]
+1 to that....but im still stuck on the install :(

**Comment by DJCrashdummy** [comment]
@iangreenleaf since this project seems to be dead for quite a while now, there is thankfully an active fork (https://github.com/RyanNoelk/OpenEats), which made a remarkable progress! (demo/showcase: https://food.ryannoelk.com/)

it also supports importing recipes from some sites (https://github.com/RyanNoelk/OpenEats/issues/177)...!
i just found this project some days ago, so i can't tell if this is done via MealMaster or whatever.

**Comment by iangreenleaf** [comment]
@DJCrashdummy thanks for the tip! Really nice to see that this project is alive elsewhere.
